GC_BUTTON_00 = 0
GC_BUTTON_01 = 1
GC_BUTTON_02 = 2
GC_BUTTON_03 = 3
GC_BUTTON_04 = 4
GC_BUTTON_05 = 5
GC_BUTTON_06 = 6
GC_BUTTON_07 = 7
GC_BUTTON_08 = 8
GC_BUTTON_09 = 9
GC_BUTTON_10 = 10
GC_BUTTON_11 = 11
GC_BUTTON_12 = 12
GC_BUTTON_13 = 13
GC_BUTTON_14 = 14
GC_BUTTON_15 = 15
GC_BUTTON_16 = 16
GC_BUTTON_17 = 17
GC_BUTTON_18 = 18
GC_BUTTON_19 = 19
GC_BUTTON_20 = 20
GC_BUTTON_21 = 21
GC_BUTTON_22 = 22
GC_BUTTON_23 = 23
GC_BUTTON_24 = 24
GC_BUTTON_25 = 25
GC_BUTTON_26 = 26
GC_BUTTON_27 = 27
GC_BUTTON_28 = 28
GC_BUTTON_29 = 29
GC_BUTTON_30 = 30
GC_BUTTON_31 = 31

GC_AXIS_00 = 60
GC_AXIS_01 = 61
GC_AXIS_02 = 62
GC_AXIS_03 = 63
GC_AXIS_04 = 64
GC_AXIS_05 = 65
GC_AXIS_06 = 66
GC_AXIS_07 = 67
GC_AXIS_08 = 68
GC_AXIS_09 = 69
GC_AXIS_10 = 70
GC_AXIS_11 = 71
GC_AXIS_12 = 72
GC_AXIS_13 = 73
GC_AXIS_14 = 74
GC_AXIS_15 = 75

ControllerInputNames = {}

ControllerInputNames["XBCD XBox Gamepad"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_a",
	[GC_BUTTON_01] = "^FE.opt_button_b",
	[GC_BUTTON_02] = "^FE.opt_button_x",
	[GC_BUTTON_03] = "^FE.opt_button_y",
	[GC_BUTTON_04] = "^FE.opt_button_dpad_left",
	[GC_BUTTON_05] = "^FE.opt_button_dpad_right",
	[GC_BUTTON_06] = "^FE.opt_button_dpad_up",
	[GC_BUTTON_07] = "^FE.opt_button_dpad_down",
	[GC_BUTTON_08] = "^FE.opt_button_black",
	[GC_BUTTON_09] = "^FE.opt_button_white",
	[GC_BUTTON_10] = "^FE.opt_button_start",
	[GC_BUTTON_11] = "^FE.opt_button_back",
	[GC_BUTTON_12] = "^FE.opt_button_left_thumbstick",
	[GC_BUTTON_13] = "^FE.opt_button_right_thumbstick",
	[GC_BUTTON_14] = "^FE.opt_button_left_trigger",
	[GC_BUTTON_15] = "^FE.opt_button_right_trigger",
	[GC_AXIS_02] = "^FE.opt_button_right_thumbstick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_thumbstick_y",
	[GC_AXIS_05] = "^FE.opt_button_left_thumbstick_y",
	[GC_AXIS_06] = "^FE.opt_button_left_thumbstick_x",
}
ControllerInputNames["Logitech RumblePad 2 USB"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_1",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_9",
	[GC_BUTTON_13] = "^FE.opt_button_10",
	[GC_BUTTON_14] = "^FE.opt_button_left_thumbstick",
	[GC_BUTTON_15] = "^FE.opt_button_right_thumbstick",
	[GC_AXIS_00] = "^FE.opt_button_right_thumbstick_x",
	[GC_AXIS_01] = "^FE.opt_button_right_thumbstick_y",
	[GC_AXIS_02] = "^FE.opt_button_left_thumbstick_x",
	[GC_AXIS_03] = "^FE.opt_button_left_thumbstick_y",
}
ControllerInputNames["Saitek P2600 Rumble Force Pad"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_1",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_black",
	[GC_BUTTON_13] = "^FE.opt_button_white",
	[GC_AXIS_00] = "^FE.opt_button_left_thumbstick_y",
	[GC_AXIS_01] = "^FE.opt_button_left_thumbstick_x",
	[GC_AXIS_02] = "^FE.opt_button_right_thumbstick_y",
	[GC_AXIS_03] = "^FE.opt_button_right_thumbstick_x",
}
ControllerInputNames["Saitek P2900 Wireless Pad"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_1",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_black",
	[GC_BUTTON_13] = "^FE.opt_button_white",
	[GC_BUTTON_14] = "^FE.opt_button_left_thumbstick",
	[GC_BUTTON_15] = "^FE.opt_button_right_thumbstick",
	[GC_AXIS_00] = "^FE.opt_button_left_thumbstick_x",
	[GC_AXIS_01] = "^FE.opt_button_left_thumbstick_y",
	[GC_AXIS_02] = "^FE.opt_button_right_thumbstick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_thumbstick_y",
}
ControllerInputNames["Saitek P990 Dual Analog Pad"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_1",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_black",
	[GC_BUTTON_13] = "^FE.opt_button_white",
	[GC_BUTTON_14] = "^FE.opt_button_left_thumbstick",
	[GC_BUTTON_15] = "^FE.opt_button_right_thumbstick",
	[GC_AXIS_00] = "^FE.opt_button_left_thumbstick_x",
	[GC_AXIS_01] = "^FE.opt_button_left_thumbstick_y",
	[GC_AXIS_02] = "^FE.opt_button_right_thumbstick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_thumbstick_y",
}
ControllerInputNames["Saitek P880 Pad"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_1",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_left_thumbstick",
	[GC_BUTTON_13] = "^FE.opt_button_right_thumbstick",
	[GC_AXIS_00] = "^FE.opt_button_left_thumbstick_x",
	[GC_AXIS_01] = "^FE.opt_button_left_thumbstick_y",
	[GC_AXIS_02] = "^FE.opt_button_right_thumbstick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_thumbstick_y",
}
ControllerInputNames["Logitech Extreme 3D Pro USB"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_trigger",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_9",
	[GC_BUTTON_13] = "^FE.opt_button_10",
	[GC_BUTTON_14] = "^FE.opt_button_11",
	[GC_BUTTON_15] = "^FE.opt_button_12",
	[GC_AXIS_02] = "^FE.opt_button_throttle",
	[GC_AXIS_03] = "^FE.opt_button_twist",
}
ControllerInputNames["Logitech Extreme 3D"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_trigger",
	[GC_BUTTON_01] = "^FE.opt_button_2",
	[GC_BUTTON_02] = "^FE.opt_button_3",
	[GC_BUTTON_03] = "^FE.opt_button_4",
	[GC_BUTTON_04] = "^FE.opt_button_hat_left",
	[GC_BUTTON_05] = "^FE.opt_button_hat_right",
	[GC_BUTTON_06] = "^FE.opt_button_hat_up",
	[GC_BUTTON_07] = "^FE.opt_button_hat_down",
	[GC_BUTTON_08] = "^FE.opt_button_5",
	[GC_BUTTON_09] = "^FE.opt_button_6",
	[GC_BUTTON_10] = "^FE.opt_button_7",
	[GC_BUTTON_11] = "^FE.opt_button_8",
	[GC_BUTTON_12] = "^FE.opt_button_9",
	[GC_BUTTON_13] = "^FE.opt_button_10",
	[GC_BUTTON_14] = "^FE.opt_button_11",
	[GC_BUTTON_15] = "^FE.opt_button_12",
	[GC_AXIS_02] = "^FE.opt_button_throttle",
	[GC_AXIS_03] = "^FE.opt_button_twist",
}
ControllerInputNames["XBOX 360 For Windows (Controller)"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_a",
	[GC_BUTTON_01] = "^FE.opt_button_b",
	[GC_BUTTON_02] = "^FE.opt_button_x",
	[GC_BUTTON_03] = "^FE.opt_button_y",
	[GC_BUTTON_04] = "^FE.opt_button_dpad_left",
	[GC_BUTTON_05] = "^FE.opt_button_dpad_right",
	[GC_BUTTON_06] = "^FE.opt_button_dpad_up",
	[GC_BUTTON_07] = "^FE.opt_button_dpad_down",
	[GC_BUTTON_08] = "^FE.opt_button_left_bumper",
	[GC_BUTTON_09] = "^FE.opt_button_right_bumper",
	[GC_BUTTON_10] = "^FE.opt_button_back",
	[GC_BUTTON_11] = "^FE.opt_button_start",
	[GC_BUTTON_12] = "^FE.opt_button_left_stick",
	[GC_BUTTON_13] = "^FE.opt_button_right_stick",
	[GC_BUTTON_21] = "^FE.opt_button_left_trigger",
	[GC_BUTTON_22] = "^FE.opt_button_right_trigger",
	[GC_AXIS_00] = "^FE.opt_button_left_stick_x",
	[GC_AXIS_01] = "^FE.opt_button_left_stick_y",
	[GC_AXIS_02] = "^FE.opt_button_right_stick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_stick_y",
	[GC_AXIS_04] = "^FE.opt_button_trigger",
}
ControllerInputNames["Controller (XBOX 360 For Windows)"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_a",
	[GC_BUTTON_01] = "^FE.opt_button_b",
	[GC_BUTTON_02] = "^FE.opt_button_x",
	[GC_BUTTON_03] = "^FE.opt_button_y",
	[GC_BUTTON_04] = "^FE.opt_button_dpad_left",
	[GC_BUTTON_05] = "^FE.opt_button_dpad_right",
	[GC_BUTTON_06] = "^FE.opt_button_dpad_up",
	[GC_BUTTON_07] = "^FE.opt_button_dpad_down",
	[GC_BUTTON_08] = "^FE.opt_button_left_bumper",
	[GC_BUTTON_09] = "^FE.opt_button_right_bumper",
	[GC_BUTTON_10] = "^FE.opt_button_back",
	[GC_BUTTON_11] = "^FE.opt_button_start",
	[GC_BUTTON_12] = "^FE.opt_button_left_stick",
	[GC_BUTTON_13] = "^FE.opt_button_right_stick",
	[GC_BUTTON_21] = "^FE.opt_button_left_trigger",
	[GC_BUTTON_22] = "^FE.opt_button_right_trigger",
	[GC_AXIS_00] = "^FE.opt_button_left_stick_x",
	[GC_AXIS_01] = "^FE.opt_button_left_stick_y",
	[GC_AXIS_02] = "^FE.opt_button_right_stick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_stick_y",
	[GC_AXIS_04] = "^FE.opt_button_trigger",
}
ControllerInputNames["Controller (Xbox 360 Wireless Receiver for Windows)"] = 
{
	[GC_BUTTON_00] = "^FE.opt_button_a",
	[GC_BUTTON_01] = "^FE.opt_button_b",
	[GC_BUTTON_02] = "^FE.opt_button_x",
	[GC_BUTTON_03] = "^FE.opt_button_y",
	[GC_BUTTON_04] = "^FE.opt_button_dpad_left",
	[GC_BUTTON_05] = "^FE.opt_button_dpad_right",
	[GC_BUTTON_06] = "^FE.opt_button_dpad_up",
	[GC_BUTTON_07] = "^FE.opt_button_dpad_down",
	[GC_BUTTON_08] = "^FE.opt_button_left_bumper",
	[GC_BUTTON_09] = "^FE.opt_button_right_bumper",
	[GC_BUTTON_10] = "^FE.opt_button_back",
	[GC_BUTTON_11] = "^FE.opt_button_start",
	[GC_BUTTON_12] = "^FE.opt_button_left_stick",
	[GC_BUTTON_13] = "^FE.opt_button_right_stick",
	[GC_BUTTON_21] = "^FE.opt_button_left_trigger",
	[GC_BUTTON_22] = "^FE.opt_button_right_trigger",
	[GC_AXIS_00] = "^FE.opt_button_left_stick_x",
	[GC_AXIS_01] = "^FE.opt_button_left_stick_y",
	[GC_AXIS_02] = "^FE.opt_button_right_stick_x",
	[GC_AXIS_03] = "^FE.opt_button_right_stick_y",
	[GC_AXIS_04] = "^FE.opt_button_trigger",
}
ControllerInputNames["Template"] = 
{
	[GC_BUTTON_00] = "GC_BUTTON_00",
	[GC_BUTTON_01] = "GC_BUTTON_01",
	[GC_BUTTON_02] = "GC_BUTTON_02",
	[GC_BUTTON_03] = "GC_BUTTON_03",
	[GC_BUTTON_04] = "GC_BUTTON_04",
	[GC_BUTTON_05] = "GC_BUTTON_05",
	[GC_BUTTON_06] = "GC_BUTTON_06",
	[GC_BUTTON_07] = "GC_BUTTON_07",
	[GC_BUTTON_08] = "GC_BUTTON_08",
	[GC_BUTTON_09] = "GC_BUTTON_09",
	[GC_BUTTON_10] = "GC_BUTTON_10",
	[GC_BUTTON_11] = "GC_BUTTON_11",
	[GC_BUTTON_12] = "GC_BUTTON_12",
	[GC_BUTTON_13] = "GC_BUTTON_13",
	[GC_BUTTON_14] = "GC_BUTTON_14",
	[GC_BUTTON_15] = "GC_BUTTON_15",
	[GC_BUTTON_16] = "GC_BUTTON_16",
	[GC_BUTTON_17] = "GC_BUTTON_17",
	[GC_BUTTON_18] = "GC_BUTTON_18",
	[GC_BUTTON_19] = "GC_BUTTON_19",
	[GC_BUTTON_20] = "GC_BUTTON_20",
	[GC_BUTTON_21] = "GC_BUTTON_21",
	[GC_BUTTON_22] = "GC_BUTTON_22",
	[GC_BUTTON_23] = "GC_BUTTON_23",
	[GC_BUTTON_24] = "GC_BUTTON_24",
	[GC_BUTTON_25] = "GC_BUTTON_25",
	[GC_BUTTON_26] = "GC_BUTTON_26",
	[GC_BUTTON_27] = "GC_BUTTON_27",
	[GC_BUTTON_28] = "GC_BUTTON_28",
	[GC_BUTTON_29] = "GC_BUTTON_29",
	[GC_BUTTON_30] = "GC_BUTTON_30",
	[GC_BUTTON_31] = "GC_BUTTON_31",
}
