PowerupClasses = 
{
	{
		["GroupName"] = "globals.powerup_airsupport",
		{
			["name"] = "globals.powerup_airsupport_cap1_name_us",
			["description"] = "globals.powerup_airsupport_cap_desc",
			["GUITextureBackGround"] = "fe\\units\\wildcat_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\cap_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_cap1_name_jap",
			["description"] = "globals.powerup_airsupport_cap_desc",
			["GUITextureBackGround"] = "fe\\units\\zero_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\cap_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_cap2_name_us",
			["description"] = "globals.powerup_airsupport_cap_desc",
			["GUITextureBackGround"] = "fe\\units\\buffalo_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\cap_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_cap2_name_jap",
			["description"] = "globals.powerup_airsupport_cap_desc",
			["GUITextureBackGround"] = "fe\\units\\oscar_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\cap_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_cap3_name_us",
			["description"] = "globals.powerup_airsupport_cap_desc",
			["GUITextureBackGround"] = "fe\\units\\lightning_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\cap_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_cap3_name_jap",
			["description"] = "globals.powerup_airsupport_cap_desc",
			["GUITextureBackGround"] = "fe\\units\\raiden_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\cap_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_dc_name_us",
			["description"] = "globals.powerup_airsupport_dc_desc",
			["GUITextureBackGround"] = "fe\\units\\dauntless_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\dc_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_dc_name_jap",
			["description"] = "globals.powerup_airsupport_dc_desc",
			["GUITextureBackGround"] = "fe\\units\\judy_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\dc_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_bomb1_name_us",
			["description"] = "globals.powerup_airsupport_bomb_desc",
			["GUITextureBackGround"] = "fe\\units\\dauntless_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\divebomb_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_bomb1_name_jap",
			["description"] = "globals.powerup_airsupport_bomb_desc",
			["GUITextureBackGround"] = "fe\\units\\judy_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\divebomb_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_bomb2_name_us",
			["description"] = "globals.powerup_airsupport_bomb_desc",
			["GUITextureBackGround"] = "fe\\units\\helldiver_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\divebomb_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_bomb2_name_jap",
			["description"] = "globals.powerup_airsupport_bomb_desc",
			["GUITextureBackGround"] = "fe\\units\\val_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\divebomb_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_torpedo1_name_us",
			["description"] = "globals.powerup_airsupport_torpedo_desc",
			["GUITextureBackGround"] = "fe\\units\\avenger_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\torpedo_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_torpedo1_name_jap",
			["description"] = "globals.powerup_airsupport_torpedo_desc",
			["GUITextureBackGround"] = "fe\\units\\kate_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\torpedo_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_levelbomb1_name_us",
			["description"] = "globals.powerup_airsupport_levelbomb_desc",
			["GUITextureBackGround"] = "fe\\units\\b17_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\levelbomb_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_levelbomb1_name_jap",
			["description"] = "globals.powerup_airsupport_levelbomb_desc",
			["GUITextureBackGround"] = "fe\\units\\betty_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\levelbomb_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_rocket1_name_us",
			["description"] = "globals.powerup_airsupport_rocket1_desc_us",
			["GUITextureBackGround"] = "fe\\units\\corsair_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\rocket_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_rocket1_name_jap",
			["description"] = "globals.powerup_airsupport_rocket1_desc_jap",
			["GUITextureBackGround"] = "fe\\units\\zero_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\kamikaze_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_torpedo2_name_us",
			["description"] = "globals.powerup_airsupport_torpedo_desc",
			["GUITextureBackGround"] = "fe\\units\\b25_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\torpedo_l.tga",
		},
		{
			["name"] = "globals.powerup_airsupport_torpedo2_name_jap",
			["description"] = "globals.powerup_airsupport_torpedo_desc",
			["GUITextureBackGround"] = "fe\\units\\nell_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\torpedo_l.tga",
		},
	},
	{
		["GroupName"] = "globals.powerup_active",
		{
			["name"] = "globals.powerup_active_evasive_manoeuvre_name",
			["description"] = "globals.powerup_active_evasive_manoeuvre_desc",
			["GUITextureBackGround"] = "fe\\powerups\\evasive.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\evasive_maneuvre_l.tga",
		},
		{
			["name"] = "globals.powerup_active_full_throttle_name",
			["description"] = "globals.powerup_active_full_throttle_desc",
			["GUITextureBackGround"] = "fe\\powerups\\fulltr.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\full_throttle_l.tga",
		},
		{
			["name"] = "globals.powerup_active_improved_ship_manoeuvreability_name",
			["description"] = "globals.powerup_active_improved_ship_manoeuvreability_desc",
			["GUITextureBackGround"] = "fe\\powerups\\man.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\improved_ship_maneuvre_l.tga",	
		},
		{
			["name"] = "globals.powerup_active_hardened_armour_name",
			["description"] = "globals.powerup_active_hardened_armour_desc",
			["GUITextureBackGround"] = "fe\\powerups\\hardened.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\hardened_armour_l.tga",	
		},
		{
			["name"] = "globals.powerup_active_improved_repair_team_name",
			["description"] = "globals.powerup_active_improved_repair_team_desc",
			["GUITextureBackGround"] = "fe\\powerups\\repteam.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\improved_repair_l.tga",
		},
		{
			["name"] = "globals.powerup_active_fierce_assault_name",
			["description"] = "globals.powerup_active_fierce_assault_desc",
			["GUITextureBackGround"] = "fe\\powerups\\fierce.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\fierce_assault_l.tga",
		},
		{
			["name"] = "globals.powerup_active_fearless_defense_name",
			["description"] = "globals.powerup_active_fearless_defense_desc",
			["GUITextureBackGround"] = "fe\\powerups\\fearless.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\fearless_defense_l.tga",
		},
		{
			["name"] = "globals.powerup_active_radar_sweep_name",
			["description"] = "globals.powerup_active_radar_sweep_desc",
			["GUITextureBackGround"] = "fe\\powerups\\radar.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\radar_sweep_l.tga",
		},
		{
			["name"] = "globals.powerup_active_improved_shells_name",
			["description"] = "globals.powerup_active_improved_shells_desc",
			["GUITextureBackGround"] = "fe\\powerups\\shell.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\improved_shells_l.tga",
		},
		{
			["name"] = "globals.powerup_active_targeting_computer_name",
			["description"] = "globals.powerup_active_targeting_computer_desc",
			["GUITextureBackGround"] = "fe\\powerups\\targeting.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\targeting_computer_l.tga",
		},
		{
			["name"] = "globals.powerup_active_automatic_reloader_name",
			["description"] = "globals.powerup_active_automatic_reloader_desc",
			["GUITextureBackGround"] = "fe\\powerups\\autoreload.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\automatic_reloader_l.tga",
		},
	},
	{
		["GroupName"] = "globals.powerup_passive",
		{
			["name"] = "globals.powerup_passive_repair_bay_name",
			["description"] = "globals.powerup_passive_repair_bay_desc",
			--["GUITextureBackGround"] = "fe\\powerups\\repairbay.tga",
			["GUITextureBackGround"] = "fe\\units\\cargo_ul.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\repair_bay_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_advanced_repair_tools_name",
			["description"] = "globals.powerup_passive_advanced_repair_tools_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advrepair.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\advanced_repair_tools_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_advanced_recon_devices_name",
			["description"] = "globals.powerup_passive_advanced_recon_devices_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advrecon.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\advanced_recon_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_veteran_crewmen_name",
			["description"] = "globals.powerup_passive_veteran_crewmen_desc",
			["GUITextureBackGround"] = "fe\\powerups\\vetcrew.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\veteran_crewmen_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_advanced_planes_name",
			["description"] = "globals.powerup_passive_advanced_planes_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advplane.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\advanced_planes_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_advanced_weapons_name",
			["description"] = "globals.powerup_passive_advanced_weapons_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advtarget.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\advanced_weapons_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_face_hardened_armour_name",
			["description"] = "globals.powerup_passive_face_hardened_armour_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advarmour.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\face_hardened_armour_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_veteran_pilots_name",
			["description"] = "globals.powerup_passive_veteran_pilots_desc",
			["GUITextureBackGround"] = "fe\\powerups\\vetpilot.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\veteran_pilots_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_heavy_assault_troops_name",
			["description"] = "globals.powerup_passive_heavy_assault_troops_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advtroop.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\heavy_assault_troops_l.tga",
		},
		{
			["name"] = "globals.powerup_passive_advanced_torpedoes_name",
			["description"] = "globals.powerup_passive_advanced_torpedoes_desc",
			["GUITextureBackGround"] = "fe\\powerups\\advtorp.tga",
			["GUITextureForeGround"] = "common\\icons\\powerup\\advanced_torpedos_l.tga",
		},
	}
}